apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.stripeSecretKey | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
