apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: ecommerce-ns
type: Opaque
stringData:
    JWT_SECRET: "super_secret_jwt_key_for_ejada_store"
    STRIPE_SECRET_KEY: "sk_test_51SywZwRtNiYE69jKmLfqpN6mTl86EBDgKZctMJ5SnYgBRXk39eLOJv2a7HZ1Cbk4aRC9UcGTBY8ICPaiEpETRQKs00m7aiJo60"
    ADMIN_EMAIL: "admin@ejadastore.com"
    ADMIN_PASSWORD: "secure_admin_password_123"
